"use client";

import Image from "next/image";
import React from "react";
import { MagnifyingGlassIcon } from "@heroicons/react/24/solid";
import Avatar from "react-avatar";
import openAi from "@/public/assets/openai_logo.png";
import { useBoardStore } from "@/store/BoardStore";

function Header() {
  const [searchString, setSearchString] = useBoardStore((state) => [
    state.searchString,
    state.setSearchString,
  ]);

  return (
    <header>
      <div className="flex flex-col md:flex-row items-center p-5 bg-gray-500/10">
        <div className="absolute top-0 left-0 w-full h-96 bg-gradient-to-br from-pink-400 to-[#0055D1] rounded-md filter blur-3xl opacity-50 -z-50" />
        <Image
          src={"https://links.papareact.com/c2cdd5"}
          alt="trello logo"
          width={300}
          height={100}
          className="w-44 md:w-56 pb-10 md:pb-0 object-contain"
        />
        <div className="flex items-center space-x-3 flex-1 justify-end">
          {/* search box */}
          <form className="flex items-center space-x-1 bg-white rounded-xl p-2 shadow-md flex-1 md:flex-initial">
            <MagnifyingGlassIcon className="h-6 w-6 text-gray-400" />
            <input
              type="text"
              placeholder="Search"
              className="flex-1 outline-none p-2"
              value={searchString}
              onChange={(e) => setSearchString(e.target.value)}
            />
            <button hidden type="submit">
              Search
            </button>
          </form>
          {/* avatar */}
          <Avatar name="Ansh Pradhan" round color="#0055D1" size="50" />
        </div>
      </div>
      {/* suggestion section, generated by gpt-4 */}
      <div className="flex items-center justify-center py-5 px-5 pt-6">
        <p className="flex items-center text-sm pr-5 shadow-xl rounded-xl w-fit bg-white italic max-w-3xl text-[#0055D1] p-2">
          <Image
            src={openAi}
            alt="gpt logo"
            width={25}
            height={25}
            className="mr-2"
          />
          GPT is summarising your tasks for the day...
        </p>
      </div>
    </header>
  );
}

export default Header;
